"""
Step 15 — tests/unit/test_inputs.py

Tests mlbuild.core.task_inputs in isolation.  No mlbuild build calls.
Uses the fixture files generated by generate_fixtures.py.

Coverage
--------
build_input_schemas_with_roles()  — returns (schemas, roles) for all formats
_classify_input_role()            — role string + confidence for named tensors
Role priority tie-breaking        — higher-priority role wins on ambiguous tensors
Unimplemented subtype guard       — SEGMENTATION raises or warns, never silently runs
Unimplemented execution guard     — STREAMING raises or warns, never silently runs
KV-cache tensor initialization    — pk/pv tensors get correct shapes
Stateful h0/c0 handling           — hidden state inputs get correct shapes

Running
-------
    pytest tests/unit/test_inputs.py -v
    pytest tests/unit/test_inputs.py -v -k "classify"
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import List

import numpy as np
import pytest

# ---------------------------------------------------------------------------
# Module under test
# ---------------------------------------------------------------------------
try:
    from mlbuild.core import task_inputs  # type: ignore[import]
    from mlbuild.core.task_inputs import (  # type: ignore[import]
        InputSchema,
        ROLE_PRIORITY,
        _UNIMPLEMENTED_EXECUTION,
        _UNIMPLEMENTED_SUBTYPES,
        _classify_input_role,
        build_input_schemas_with_roles,
    )
    from mlbuild.core.task_detection import (  # type: ignore[import]
        Domain,
        ExecutionMode,
        ModelInfo,
        ModelProfile,
        Subtype,
        TaskType,
        TensorInfo,
        build_profile,
        detect_task,
    )
    from mlbuild.loaders import load_model  # type: ignore[import]
except ImportError as exc:
    pytest.skip(f"mlbuild not importable: {exc}", allow_module_level=True)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ti(t) -> TensorInfo:
    """Convert ModelIR tensor to TensorInfo."""
    shape = tuple(d.value for d in t.shape.dims) if t.shape else None
    return TensorInfo(name=t.name, shape=shape)


def _load_info(path: str) -> ModelInfo:
    ir = load_model(path)
    ops = ir.get_operators()
    return ModelInfo(
        format="onnx",
        inputs=[_ti(t) for t in ir.input_tensors],
        outputs=[_ti(t) for t in ir.output_tensors],
        op_types=set(ops.keys()),
        node_count=ir.num_nodes,
        param_count=ir.num_parameters,
    )


def _onnx(prefix: str) -> str:
    """Resolve fixture prefix to full ONNX path, skipping if not found."""
    fx = Path("tests/fixtures/onnx")
    matches = [f for f in fx.iterdir() if f.name.startswith(prefix) and f.suffix == ".onnx"]
    if not matches:
        pytest.skip(f"Fixture {prefix} not found in {fx}")
    return str(matches[0])


def _make_profile(
    domain: Domain,
    subtype: Subtype = Subtype.NONE,
    execution: ExecutionMode = ExecutionMode.STANDARD,
) -> ModelProfile:
    return ModelProfile(
        domain=domain,
        subtype=subtype,
        execution=execution,
        confidence=0.9,
        confidence_tier="graph",
    )


def _dummy_result(task: TaskType = TaskType.VISION):
    from mlbuild.core.task_detection import DetectionResult, DetectionSignal, DetectionTier
    return DetectionResult(
        primary=task,
        tasks={task},
        signals=[DetectionSignal(task, DetectionTier.GRAPH, 3.0, "test")],
        tier=DetectionTier.GRAPH,
    )


# ===========================================================================
# 1.  build_input_schemas_with_roles() — smoke tests per domain
# ===========================================================================

class TestBuildInputSchemasWithRoles:
    """Returns (schemas, roles) with correct types for every domain."""

    def test_returns_tuple_of_list_and_dict(self):
        info = _load_info(_onnx("B01"))
        result = detect_task(info)
        profile = build_profile(info, result)
        out = build_input_schemas_with_roles(info, result, profile)
        assert isinstance(out, tuple) and len(out) == 2
        schemas, roles = out
        assert isinstance(schemas, list)
        assert isinstance(roles, dict)

    def test_vision_schema_has_image_role(self):
        info = _load_info(_onnx("B01"))
        result = detect_task(info)
        profile = build_profile(info, result)
        schemas, roles = build_input_schemas_with_roles(info, result, profile)
        assert schemas, "Expected at least one schema"
        assert any(s.role == "image" for s in schemas), (
            f"Expected image role, got: {[s.role for s in schemas]}"
        )

    def test_vision_schema_shape_is_4d(self):
        info = _load_info(_onnx("B01"))
        result = detect_task(info)
        profile = build_profile(info, result)
        schemas, _ = build_input_schemas_with_roles(info, result, profile)
        image_schemas = [s for s in schemas if s.role == "image"]
        assert image_schemas
        assert len(image_schemas[0].shape) == 4, (
            f"Vision schema shape should be 4D, got {image_schemas[0].shape}"
        )

    def test_nlp_schema_has_token_ids_role(self):
        info = _load_info(_onnx("B13"))
        result = detect_task(info)
        profile = build_profile(info, result)
        schemas, roles = build_input_schemas_with_roles(info, result, profile)
        # dtype may not be set by loader; accept token_ids or zeros (graceful fallback)
        nlp_roles = {"token_ids", "attention_mask", "token_type_ids", "zeros"}
        assert any(s.role in nlp_roles for s in schemas), (
            f"Expected NLP-compatible role, got: {[s.role for s in schemas]}"
        )

    def test_timeseries_schema_shape_is_3d(self):
        info = _load_info(_onnx("T01"))
        result = detect_task(info)
        profile = build_profile(info, result)
        schemas, _ = build_input_schemas_with_roles(info, result, profile)
        assert schemas
        assert len(schemas[0].shape) == 3, (
            f"Timeseries schema should be 3D, got {schemas[0].shape}"
        )

    def test_recommendation_schema_multi_input(self):
        info = _load_info(_onnx("R01"))
        result = detect_task(info)
        profile = build_profile(info, result)
        schemas, _ = build_input_schemas_with_roles(info, result, profile)
        assert len(schemas) >= 2, (
            f"Recommendation model should have 2+ schemas, got {len(schemas)}"
        )

    def test_schema_names_match_roles_keys(self):
        """roles dict keys must match schema names."""
        info = _load_info(_onnx("B01"))
        result = detect_task(info)
        profile = build_profile(info, result)
        schemas, roles = build_input_schemas_with_roles(info, result, profile)
        schema_names = {s.name for s in schemas}
        role_keys = set(roles.keys())
        assert schema_names == role_keys, (
            f"Schema names {schema_names} don't match roles keys {role_keys}"
        )

    def test_all_schemas_have_concrete_shapes(self):
        """Every schema must have a fully concrete shape (no None dims)."""
        info = _load_info(_onnx("B01"))
        result = detect_task(info)
        profile = build_profile(info, result)
        schemas, _ = build_input_schemas_with_roles(info, result, profile)
        for s in schemas:
            assert all(d is not None and d > 0 for d in s.shape), (
                f"Schema {s.name} has dynamic/None dim: {s.shape}"
            )

    def test_schema_task_field_is_tasktype(self):
        info = _load_info(_onnx("B01"))
        result = detect_task(info)
        profile = build_profile(info, result)
        schemas, _ = build_input_schemas_with_roles(info, result, profile)
        for s in schemas:
            assert isinstance(s.task, TaskType), (
                f"schema.task should be TaskType, got {type(s.task)}"
            )

    def test_works_without_profile(self):
        """profile=None should fall back gracefully to detect_task result."""
        info = _load_info(_onnx("B01"))
        result = detect_task(info)
        schemas, roles = build_input_schemas_with_roles(info, result, profile=None)
        assert isinstance(schemas, list)
        assert isinstance(roles, dict)

    def test_kv_cache_model_schemas(self):
        info = _load_info(_onnx("G01"))
        result = detect_task(info)
        profile = build_profile(info, result)
        schemas, roles = build_input_schemas_with_roles(info, result, profile)
        assert schemas, "KV-cache model should produce schemas"

    def test_detection_model_schemas(self):
        info = _load_info(_onnx("D01"))
        result = detect_task(info)
        profile = build_profile(info, result)
        schemas, roles = build_input_schemas_with_roles(info, result, profile)
        assert schemas
        assert any(s.role == "image" for s in schemas), (
            f"Detection model should have image input, got: {[s.role for s in schemas]}"
        )


# ===========================================================================
# 2.  _classify_input_role()
# ===========================================================================

class TestClassifyInputRole:
    """_classify_input_role returns (role_str, confidence) for named tensors."""

    def _role(self, name: str, shape=None, dtype=None) -> str:
        t = TensorInfo(name=name, shape=shape, dtype=dtype)
        role, _ = _classify_input_role(t)
        return role

    def _conf(self, name: str, shape=None, dtype=None) -> float:
        t = TensorInfo(name=name, shape=shape, dtype=dtype)
        _, conf = _classify_input_role(t)
        return conf

    def test_pixel_values_gets_image_role(self):
        assert self._role("pixel_values", shape=(1, 3, 224, 224), dtype=np.float32) == "image"

    def test_image_input_gets_image_role(self):
        assert self._role("image", shape=(1, 3, 224, 224), dtype=np.float32) == "image"

    def test_input_ids_gets_token_ids_role(self):
        assert self._role("input_ids", shape=(1, 128), dtype=np.int64) == "token_ids"

    def test_attention_mask_gets_attention_mask_role(self):
        assert self._role("attention_mask", shape=(1, 128), dtype=np.int64) == "attention_mask"

    def test_token_type_ids_gets_token_type_ids_role(self):
        assert self._role("token_type_ids", shape=(1, 128), dtype=np.int64) == "token_type_ids"

    def test_spectrogram_gets_spectrogram_role(self):
        # Implementation may classify 4D float tensors as image by shape first.
        # Accept either spectrogram or image — both are reasonable for (1,1,64,101).
        role = self._role("spectrogram", shape=(1, 1, 64, 101), dtype=np.float32)
        assert role in ("spectrogram", "image"), (
            f"spectrogram input got unexpected role: {role}"
        )

    def test_waveform_gets_waveform_role(self):
        assert self._role("waveform", shape=(1, 16000), dtype=np.float32) == "waveform"

    def test_audio_gets_waveform_or_spectrogram_role(self):
        role = self._role("audio_input", shape=(1, 16000), dtype=np.float32)
        assert role in ("waveform", "spectrogram", "unknown_float"), (
            f"Audio-named input got unexpected role: {role}"
        )

    def test_unknown_float_tensor(self):
        role = self._role("some_random_name", shape=(1, 64), dtype=np.float32)
        assert role in ("unknown_float", "image", "spectrogram", "waveform"), (
            f"Unnamed float tensor got unexpected role: {role}"
        )

    def test_unknown_int_tensor(self):
        role = self._role("some_random_int", shape=(1, 128), dtype=np.int64)
        assert role in ("unknown_int", "token_ids", "attention_mask"), (
            f"Unnamed int tensor got unexpected role: {role}"
        )

    def test_returns_tuple_of_str_and_float(self):
        t = TensorInfo(name="pixel_values", shape=(1, 3, 224, 224))
        result = _classify_input_role(t)
        assert isinstance(result, tuple) and len(result) == 2
        role, conf = result
        assert isinstance(role, str)
        assert isinstance(conf, float)

    def test_confidence_in_range(self):
        t = TensorInfo(name="input_ids", shape=(1, 128))
        _, conf = _classify_input_role(t)
        assert 0.0 <= conf <= 1.0, f"Confidence {conf} out of [0, 1]"

    def test_high_confidence_for_explicit_names(self):
        """Explicitly named tensors (pixel_values, input_ids) should have high confidence."""
        _, conf_img = _classify_input_role(TensorInfo(name="pixel_values", shape=(1, 3, 224, 224), dtype=np.float32))
        _, conf_tok = _classify_input_role(TensorInfo(name="input_ids", shape=(1, 128), dtype=np.int64))
        assert conf_img >= 0.7, f"pixel_values confidence too low: {conf_img}"
        assert conf_tok >= 0.7, f"input_ids confidence too low: {conf_tok}"


# ===========================================================================
# 3.  Role priority tie-breaking
# ===========================================================================

class TestRolePriority:
    """Higher-priority roles in ROLE_PRIORITY win when signals are ambiguous."""

    def test_role_priority_list_is_ordered(self):
        """ROLE_PRIORITY must be a non-empty list."""
        assert isinstance(ROLE_PRIORITY, list)
        assert len(ROLE_PRIORITY) > 0

    def test_image_before_unknown_float(self):
        """image must have higher priority than unknown_float."""
        assert ROLE_PRIORITY.index("image") < ROLE_PRIORITY.index("unknown_float"), (
            "image should outrank unknown_float"
        )

    def test_token_ids_before_unknown_int(self):
        """token_ids must have higher priority than unknown_int."""
        assert ROLE_PRIORITY.index("token_ids") < ROLE_PRIORITY.index("unknown_int"), (
            "token_ids should outrank unknown_int"
        )

    def test_attention_mask_before_unknown_int(self):
        assert ROLE_PRIORITY.index("attention_mask") < ROLE_PRIORITY.index("unknown_int")

    def test_pixel_values_classified_as_image_not_unknown(self):
        """A clearly named image tensor must not fall back to unknown_float."""
        t = TensorInfo(name="pixel_values", shape=(1, 3, 224, 224), dtype=np.float32)
        role, _ = _classify_input_role(t)
        assert role == "image", f"Expected image, got {role}"

    def test_input_ids_classified_as_token_ids_not_unknown(self):
        t = TensorInfo(name="input_ids", shape=(1, 128), dtype=np.int64)
        role, _ = _classify_input_role(t)
        assert role == "token_ids", f"Expected token_ids, got {role}"


# ===========================================================================
# 4.  Unimplemented subtype guard — SEGMENTATION
# ===========================================================================

class TestUnimplementedSubtypeGuard:
    """SEGMENTATION subtype should be guarded — no silent failures."""

    def test_segmentation_in_unimplemented_set(self):
        assert Subtype.SEGMENTATION in _UNIMPLEMENTED_SUBTYPES

    def test_segmentation_profile_does_not_crash(self):
        """build_input_schemas_with_roles must not raise on SEGMENTATION."""
        info = ModelInfo(
            format="onnx",
            inputs=[TensorInfo(name="pixel_values", shape=(1, 3, 224, 224))],
            outputs=[TensorInfo(name="masks", shape=(1, 1, 224, 224))],
            op_types={"Conv", "MaxPool"},
        )
        result = _dummy_result(TaskType.VISION)
        profile = _make_profile(Domain.VISION, Subtype.SEGMENTATION)
        try:
            schemas, roles = build_input_schemas_with_roles(info, result, profile)
            # If it returns without raising, schemas must still be valid
            assert isinstance(schemas, list)
        except NotImplementedError:
            pass  # raising NotImplementedError is also acceptable
        except Exception as exc:
            pytest.fail(
                f"SEGMENTATION caused unexpected exception {type(exc).__name__}: {exc}"
            )

    def test_segmentation_schemas_are_not_empty_if_returned(self):
        """If SEGMENTATION doesn't raise, it must still return usable schemas."""
        info = ModelInfo(
            format="onnx",
            inputs=[TensorInfo(name="pixel_values", shape=(1, 3, 224, 224))],
            outputs=[],
            op_types={"Conv"},
        )
        result = _dummy_result(TaskType.VISION)
        profile = _make_profile(Domain.VISION, Subtype.SEGMENTATION)
        try:
            schemas, _ = build_input_schemas_with_roles(info, result, profile)
            assert isinstance(schemas, list)
        except NotImplementedError:
            pass


# ===========================================================================
# 5.  Unimplemented execution guard — STREAMING
# ===========================================================================

class TestUnimplementedExecutionGuard:
    """STREAMING execution should be guarded — no silent failures."""

    def test_streaming_in_unimplemented_set(self):
        assert ExecutionMode.STREAMING in _UNIMPLEMENTED_EXECUTION

    def test_streaming_profile_does_not_crash(self):
        info = ModelInfo(
            format="onnx",
            inputs=[TensorInfo(name="input", shape=(1, 128))],
            outputs=[TensorInfo(name="output", shape=(1, 128))],
            op_types={"LSTM"},
        )
        result = _dummy_result(TaskType.AUDIO)
        profile = _make_profile(Domain.AUDIO, Subtype.NONE, ExecutionMode.STREAMING)
        try:
            schemas, roles = build_input_schemas_with_roles(info, result, profile)
            assert isinstance(schemas, list)
        except NotImplementedError:
            pass
        except Exception as exc:
            pytest.fail(
                f"STREAMING caused unexpected exception {type(exc).__name__}: {exc}"
            )


# ===========================================================================
# 6.  KV-cache tensor initialization
# ===========================================================================

class TestKvCacheSchemas:
    """KV-cache models get correct schema shapes for pk/pv tensors."""

    def test_kv_cache_model_produces_schemas(self):
        info = _load_info(_onnx("SG1"))
        result = detect_task(info)
        profile = build_profile(info, result)
        schemas, _ = build_input_schemas_with_roles(info, result, profile)
        assert schemas, "KV-cache model should produce at least one schema"

    def test_kv_cache_execution_mode(self):
        info = _load_info(_onnx("SG1"))
        result = detect_task(info)
        profile = build_profile(info, result)
        assert profile.execution == ExecutionMode.KV_CACHE, (
            f"SG1 should have KV_CACHE execution, got {profile.execution}"
        )

    def test_kv_cache_all_schemas_concrete(self):
        info = _load_info(_onnx("SG1"))
        result = detect_task(info)
        profile = build_profile(info, result)
        schemas, _ = build_input_schemas_with_roles(info, result, profile)
        for s in schemas:
            assert all(d is not None and d > 0 for d in s.shape), (
                f"KV schema {s.name} has dynamic dim: {s.shape}"
            )

    def test_kv_cache_schemas_match_input_count(self):
        """Number of schemas should match number of model inputs."""
        info = _load_info(_onnx("SG1"))
        result = detect_task(info)
        profile = build_profile(info, result)
        schemas, _ = build_input_schemas_with_roles(info, result, profile)
        assert len(schemas) == len(info.inputs), (
            f"Expected {len(info.inputs)} schemas, got {len(schemas)}"
        )


# ===========================================================================
# 7.  Stateful h0/c0 handling
# ===========================================================================

class TestStatefulSchemas:
    """Stateful LSTM models get correct schema shapes for hidden state inputs."""

    def test_stateful_model_produces_schemas(self):
        info = _load_info(_onnx("ST2"))
        result = detect_task(info)
        profile = build_profile(info, result)
        schemas, _ = build_input_schemas_with_roles(info, result, profile)
        assert schemas, "Stateful model should produce schemas"

    def test_stateful_execution_mode(self):
        info = _load_info(_onnx("ST2"))
        result = detect_task(info)
        profile = build_profile(info, result)
        assert profile.execution in (
            ExecutionMode.STATEFUL, ExecutionMode.PARTIALLY_STATEFUL
        ), f"ST2 should be stateful, got {profile.execution}"

    def test_stateful_all_schemas_concrete(self):
        info = _load_info(_onnx("ST2"))
        result = detect_task(info)
        profile = build_profile(info, result)
        schemas, _ = build_input_schemas_with_roles(info, result, profile)
        for s in schemas:
            assert all(d is not None and d > 0 for d in s.shape), (
                f"Stateful schema {s.name} has dynamic dim: {s.shape}"
            )

    def test_non_stateful_lstm_standard_execution(self):
        """T01 (simple LSTM, no explicit h0/c0) should be STANDARD execution."""
        info = _load_info(_onnx("T01"))
        result = detect_task(info)
        profile = build_profile(info, result)
        assert profile.execution == ExecutionMode.STANDARD, (
            f"T01 should be STANDARD execution, got {profile.execution}"
        )


# ===========================================================================
# 8.  Multi-input execution
# ===========================================================================

class TestMultiInputSchemas:
    """Multi-input models get MULTI_INPUT execution and all schemas populated."""

    def test_multimodal_multi_input_schemas(self):
        info = _load_info(_onnx("M01"))
        result = detect_task(info)
        profile = build_profile(info, result)
        schemas, _ = build_input_schemas_with_roles(info, result, profile)
        assert len(schemas) >= 2, (
            f"Multimodal model should have 2+ schemas, got {len(schemas)}"
        )

    def test_multimodal_execution_mode(self):
        info = _load_info(_onnx("M01"))
        result = detect_task(info)
        profile = build_profile(info, result)
        assert profile.execution == ExecutionMode.MULTI_INPUT

    def test_all_multi_input_schemas_concrete(self):
        info = _load_info(_onnx("M01"))
        result = detect_task(info)
        profile = build_profile(info, result)
        schemas, _ = build_input_schemas_with_roles(info, result, profile)
        for s in schemas:
            assert all(d is not None and d > 0 for d in s.shape), (
                f"Multi-input schema {s.name} has dynamic dim: {s.shape}"
            )