"""
Step 14 — tests/unit/test_detection.py

Tests mlbuild.core.task_detection in isolation.  No mlbuild build calls.
Uses the fixture files generated by generate_fixtures.py and the session
fixtures from conftest.py.

Coverage
--------
build_profile()          — top-level entrypoint, all 50 non-failure models
_score_detection()       — NMS op presence, output shape heuristics
_detect_kv_cache()       — past_key_values tensor pattern
_detect_stateful()       — h0/c0/hidden_state tensor pattern
_score_timeseries()      — LSTM/GRU op presence, TCN Conv1d pattern
_score_recommendation()  — Gather op + embedding-like output shape

Running
-------
    # From repo root — requires fixtures to have been generated first.
    pytest tests/unit/test_detection.py -v

    # Fast subset (ONNX only, skips CoreML/TFLite):
    pytest tests/unit/test_detection.py -v -k "onnx"

    # Single model:
    pytest tests/unit/test_detection.py -v -k "B01"
"""

from __future__ import annotations

import importlib
import sys
from pathlib import Path
from typing import Any

import pytest

# ---------------------------------------------------------------------------
# Module under test
# ---------------------------------------------------------------------------
try:
    from mlbuild.core import task_detection  # type: ignore[import]
    from mlbuild.core.task_detection import (  # type: ignore[import]
        ModelInfo,
        ModelProfile,
        TensorInfo,
        build_profile,
        detect_task,
        extract_coreml_info,
        extract_tflite_info,
    )
    from mlbuild.loaders import load_model  # type: ignore[import]
except ImportError as exc:
    pytest.skip(
        f"mlbuild not importable: {exc}",
        allow_module_level=True,
    )

# ---------------------------------------------------------------------------
# Private helpers — scoring functions tested directly for isolation
# ---------------------------------------------------------------------------

def _get(fn_name: str):
    """Return a private function from task_detection, or None if absent."""
    return getattr(task_detection, fn_name, None)


_score_detection      = _get("_score_detection")
_detect_kv_cache      = _get("_detect_kv_cache")
_detect_stateful      = _get("_detect_stateful")
_score_timeseries     = _get("_score_timeseries")
_score_recommendation = _get("_score_recommendation")


# ===========================================================================
# Core helper — path → ModelProfile via the real API chain
# ===========================================================================

def _model_info_from_path(path: Path) -> "ModelInfo":
    """
    Build a ModelInfo from any supported model file.

    ONNX  : load_model(path) → ModelIR → ModelInfo built from ir fields
    CoreML: extract_coreml_info(path) → ModelInfo
    TFLite: extract_tflite_info(path) → ModelInfo
    """
    suffix = path.suffix.lower()

    if suffix == ".onnx":
        ir = load_model(str(path))

        def _to_tensor_info(t) -> TensorInfo:
            shape = tuple(d.value for d in t.shape.dims) if t.shape is not None else None
            return TensorInfo(name=t.name, shape=shape)

        ops = ir.get_operators()
        op_types = set(ops.keys()) if isinstance(ops, dict) else set(ops)

        return ModelInfo(
            format      = "onnx",
            inputs      = [_to_tensor_info(t) for t in ir.input_tensors],
            outputs     = [_to_tensor_info(t) for t in ir.output_tensors],
            op_types    = op_types,
            node_count  = ir.num_nodes,
            param_count = ir.num_parameters,
        )

    elif suffix in (".mlmodel", ".mlpackage") or path.is_dir():
        return extract_coreml_info(str(path))

    elif suffix == ".tflite":
        return extract_tflite_info(str(path))

    else:
        pytest.skip(f"Unsupported model format: {path.suffix}")


def _run_build_profile(path: Path) -> "ModelProfile":
    """Full path → ModelProfile using the real API chain."""
    info   = _model_info_from_path(path)
    result = detect_task(info)
    return build_profile(info, result)


def _model_info_for_scoring(path: Path) -> "ModelInfo":
    """Get ModelInfo for an ONNX path (scoring fns require ONNX-derived info)."""
    if path.suffix.lower() != ".onnx":
        pytest.skip(f"Scoring tests require ONNX model, got {path.suffix}")
    return _model_info_from_path(path)


# ===========================================================================
# 1.  build_profile() — parametrised over every non-failure model
# ===========================================================================

def _all_non_failure_ids(manifest_data: dict) -> list[str]:
    """Return model IDs where expected_failure is False (or absent)."""
    models = manifest_data.get("models", manifest_data)  # handle both shapes
    return [
        mid
        for mid, entry in models.items()
        if not entry.get("expected_failure", False)
    ]


def pytest_generate_tests(metafunc):
    """Parametrise TestBuildProfile with every non-failure model ID."""
    if (
        "model_id" in metafunc.fixturenames
        and metafunc.cls is not None
        and metafunc.cls.__name__ == "TestBuildProfile"
    ):
        manifest_path = (
            Path(__file__).parent.parent / "fixtures" / "manifest.json"
        )
        if not manifest_path.exists():
            metafunc.parametrize("model_id", [])
            return

        import json

        with manifest_path.open() as fh:
            data = json.load(fh)

        ids = _all_non_failure_ids(data)
        metafunc.parametrize("model_id", ids, ids=ids)


class TestBuildProfile:
    """build_profile() returns the expected ModelProfile for every fixture."""

    def test_domain_matches_manifest(
        self,
        model_id: str,
        fixture_path,
        expected_profile,
    ):
        """profile.domain == manifest expected_domain."""
        path = fixture_path(model_id)
        if path is None or not Path(path).exists():
            pytest.skip(f"Fixture file not found for {model_id}")

        profile = _run_build_profile(path)
        exp = expected_profile(model_id)

        assert profile.domain == exp["domain"], (
            f"[{model_id}] domain mismatch: "
            f"got {profile.domain!r}, expected {exp['domain']!r}"
        )

    def test_subtype_matches_manifest(
        self,
        model_id: str,
        fixture_path,
        expected_profile,
    ):
        """profile.subtype == manifest expected_subtype."""
        path = fixture_path(model_id)
        if path is None or not Path(path).exists():
            pytest.skip(f"Fixture file not found for {model_id}")

        profile = _run_build_profile(path)
        exp = expected_profile(model_id)

        assert profile.subtype == exp["subtype"], (
            f"[{model_id}] subtype mismatch: "
            f"got {profile.subtype!r}, expected {exp['subtype']!r}"
        )

    def test_execution_matches_manifest(
        self,
        model_id: str,
        fixture_path,
        expected_profile,
    ):
        """profile.execution == manifest expected_execution."""
        path = fixture_path(model_id)
        if path is None or not Path(path).exists():
            pytest.skip(f"Fixture file not found for {model_id}")

        profile = _run_build_profile(path)
        exp = expected_profile(model_id)

        assert profile.execution == exp["execution"], (
            f"[{model_id}] execution mismatch: "
            f"got {profile.execution!r}, expected {exp['execution']!r}"
        )

    def test_profile_is_modelprofile_instance(
        self,
        model_id: str,
        fixture_path,
    ):
        """build_profile() always returns a ModelProfile, never None."""
        path = fixture_path(model_id)
        if path is None or not Path(path).exists():
            pytest.skip(f"Fixture file not found for {model_id}")

        profile = _run_build_profile(path)
        assert isinstance(profile, ModelProfile), (
            f"[{model_id}] build_profile() returned {type(profile)}, "
            f"expected ModelProfile"
        )


# ===========================================================================
# 2.  _score_detection()
# ===========================================================================

@pytest.mark.skipif(
    _score_detection is None,
    reason="_score_detection not exported from task_detection",
)
class TestScoreDetection:
    """_score_detection() returns a positive score for detection models."""

    @pytest.mark.parametrize("mid", ["D01", "D02", "D03", "D04"])
    def test_detection_models_score_positively(self, mid: str, fixture_path):
        """Detection fixture models should yield score > 0."""
        path = fixture_path(mid)
        if path is None or not Path(path).exists():
            pytest.skip(f"Fixture {mid} not available")
        if Path(path).suffix != ".onnx":
            pass  # _model_info_for_scoring handles the skip

        info = _model_info_for_scoring(Path(path))
        score = _score_detection(info)[0]
        assert score > 0, (
            f"[{mid}] expected positive detection score, got {score}"
        )

    @pytest.mark.parametrize("mid", ["B01", "B05", "B09", "B13"])
    def test_non_detection_models_score_zero_or_low(
        self, mid: str, fixture_path
    ):
        """Baseline non-detection models should not produce a detection score."""
        path = fixture_path(mid)
        if path is None or not Path(path).exists():
            pytest.skip(f"Fixture {mid} not available")
        if Path(path).suffix != ".onnx":
            pass  # _model_info_for_scoring handles the skip

        info = _model_info_for_scoring(Path(path))
        score = _score_detection(info)[0]
        assert score < 0.5, (
            f"[{mid}] unexpected detection score {score:.3f} for a "
            f"non-detection model"
        )

    @pytest.mark.parametrize("mid", ["SD2"])
    def test_nms_baked_detection_model_scores_high(
        self, mid: str, fixture_path
    ):
        """SD2 (baked NMS) should still score as detection."""
        path = fixture_path(mid)
        if path is None or not Path(path).exists():
            pytest.skip(f"Fixture {mid} not available")
        if Path(path).suffix != ".onnx":
            pass  # _model_info_for_scoring handles the skip

        info = _model_info_for_scoring(Path(path))
        score = _score_detection(info)[0]
        assert score > 0, (
            f"[{mid}] baked-NMS model should score as detection"
        )


# ===========================================================================
# 3.  _detect_kv_cache()
# ===========================================================================

@pytest.mark.skipif(
    _detect_kv_cache is None,
    reason="_detect_kv_cache not exported from task_detection",
)
class TestDetectKvCache:
    """_detect_kv_cache() fires only on KV-cache models."""

    @pytest.mark.parametrize("mid", ["G01", "SG1"])
    def test_kv_cache_models_detected(self, mid: str, fixture_path):
        """Generative models with KV-cache tensors should return True."""
        path = fixture_path(mid)
        if path is None or not Path(path).exists():
            pytest.skip(f"Fixture {mid} not available")
        if Path(path).suffix != ".onnx":
            pass  # _model_info_for_scoring handles the skip

        info = _model_info_for_scoring(Path(path))
        _detect_kv_cache(info)[0] is True, (
            f"[{mid}] KV-cache model not detected"
        )

    @pytest.mark.parametrize("mid", ["B01", "B13", "T01", "D01"])
    def test_non_kv_cache_models_not_detected(
        self, mid: str, fixture_path
    ):
        """Models without KV-cache tensors should return False."""
        path = fixture_path(mid)
        if path is None or not Path(path).exists():
            pytest.skip(f"Fixture {mid} not available")
        if Path(path).suffix != ".onnx":
            pass  # _model_info_for_scoring handles the skip

        info = _model_info_for_scoring(Path(path))
        _detect_kv_cache(info)[0] is False, (
            f"[{mid}] false positive KV-cache detection"
        )


# ===========================================================================
# 4.  _detect_stateful()
# ===========================================================================

@pytest.mark.skipif(
    _detect_stateful is None,
    reason="_detect_stateful not exported from task_detection",
)
class TestDetectStateful:
    """_detect_stateful() fires only on stateful LSTM/GRU models."""

    @pytest.mark.parametrize("mid", ["ST2"])
    def test_stateful_lstm_detected(self, mid: str, fixture_path):
        """ST2 has explicit h0/c0 — should return True."""
        path = fixture_path(mid)
        if path is None or not Path(path).exists():
            pytest.skip(f"Fixture {mid} not available")
        if Path(path).suffix != ".onnx":
            pass  # _model_info_for_scoring handles the skip

        info = _model_info_for_scoring(Path(path))
        assert _detect_stateful(info)[0] is True, (
            f"[{mid}] stateful LSTM not detected"
        )

    @pytest.mark.parametrize("mid", ["T01", "B01", "G01"])
    def test_non_stateful_models_not_detected(
        self, mid: str, fixture_path
    ):
        """Models without explicit hidden-state inputs should return False."""
        path = fixture_path(mid)
        if path is None or not Path(path).exists():
            pytest.skip(f"Fixture {mid} not available")
        if Path(path).suffix != ".onnx":
            pass  # _model_info_for_scoring handles the skip

        info = _model_info_for_scoring(Path(path))
        assert _detect_stateful(info)[0] is False, (
            f"[{mid}] false positive stateful detection"
        )


# ===========================================================================
# 5.  _score_timeseries()
# ===========================================================================

@pytest.mark.skipif(
    _score_timeseries is None,
    reason="_score_timeseries not exported from task_detection",
)
class TestScoreTimeseries:
    """_score_timeseries() returns a positive score for time-series models."""

    @pytest.mark.parametrize("mid", ["T01", "T02", "ST1", "ST2"])
    def test_timeseries_models_score_positively(
        self, mid: str, fixture_path
    ):
        """LSTM/GRU/TCN models should yield score > 0."""
        path = fixture_path(mid)
        if path is None or not Path(path).exists():
            pytest.skip(f"Fixture {mid} not available")
        if Path(path).suffix != ".onnx":
            pass  # _model_info_for_scoring handles the skip

        info = _model_info_for_scoring(Path(path))
        score = _score_timeseries(info)
        assert score > 0, (
            f"[{mid}] expected positive timeseries score, got {score}"
        )

    @pytest.mark.parametrize("mid", ["B01", "D01", "R01"])
    def test_non_timeseries_models_score_low(
        self, mid: str, fixture_path
    ):
        """Non-timeseries models should not trigger time-series scoring."""
        path = fixture_path(mid)
        if path is None or not Path(path).exists():
            pytest.skip(f"Fixture {mid} not available")
        if Path(path).suffix != ".onnx":
            pass  # _model_info_for_scoring handles the skip

        info = _model_info_for_scoring(Path(path))
        score = _score_timeseries(info)
        assert score < 0.5, (
            f"[{mid}] unexpected timeseries score {score:.3f}"
        )


# ===========================================================================
# 6.  _score_recommendation()
# ===========================================================================

@pytest.mark.skipif(
    _score_recommendation is None,
    reason="_score_recommendation not exported from task_detection",
)
class TestScoreRecommendation:
    """_score_recommendation() returns a positive score for rec models."""

    @pytest.mark.parametrize("mid", ["R01", "R02", "SR1"])
    def test_recommendation_models_score_positively(
        self, mid: str, fixture_path
    ):
        """Gather-based embedding models should yield score > 0."""
        path = fixture_path(mid)
        if path is None or not Path(path).exists():
            pytest.skip(f"Fixture {mid} not available")
        if Path(path).suffix != ".onnx":
            pass  # _model_info_for_scoring handles the skip

        info = _model_info_for_scoring(Path(path))
        score = _score_recommendation(info)[0]
        assert score > 0, (
            f"[{mid}] expected positive recommendation score, got {score}"
        )

    @pytest.mark.parametrize("mid", ["B01", "T01", "D01"])
    def test_non_rec_models_score_low(self, mid: str, fixture_path):
        """Non-recommendation models should not trigger rec scoring."""
        path = fixture_path(mid)
        if path is None or not Path(path).exists():
            pytest.skip(f"Fixture {mid} not available")
        if Path(path).suffix != ".onnx":
            pass  # _model_info_for_scoring handles the skip

        info = _model_info_for_scoring(Path(path))
        score = _score_recommendation(info)[0]
        assert score < 0.5, (
            f"[{mid}] unexpected recommendation score {score:.3f}"
        )


# ===========================================================================
# 7.  Failure models — build_profile() must still return a profile
#     (detection never raises; the failure happens downstream at conversion)
# ===========================================================================

class TestFailureModels:
    """build_profile() on expected-failure sources must not raise."""

    @pytest.mark.parametrize("mid", ["S09", "S10", "SD2", "SM2", "SG2"])
    def test_build_profile_does_not_raise_on_failure_fixtures(
        self, mid: str, fixture_path
    ):
        """Detection on a broken model must not throw — it just profiles."""
        path = fixture_path(mid)
        if path is None or not Path(path).exists():
            pytest.skip(f"Fixture {mid} not available")

        # Should never raise — failures are conversion-time, not detect-time.
        try:
            profile = _run_build_profile(path)
            assert isinstance(profile, ModelProfile)
        except Exception as exc:
            pytest.fail(
                f"[{mid}] build_profile() raised unexpectedly: {exc}"
            )


# ===========================================================================
# 8.  Smoke test — build_profile() accepts both str and Path inputs
# ===========================================================================

class TestBuildProfileInputTypes:
    """build_profile() accepts str paths as well as pathlib.Path objects."""

    def test_accepts_string_path(self, fixture_path):
        """Passing a str instead of Path must work identically."""
        path = fixture_path("B01")
        if path is None or not Path(path).exists():
            pytest.skip("B01 fixture not available")

        profile_str  = _run_build_profile(Path(path))
        profile_path = _run_build_profile(Path(path))

        assert profile_str.domain    == profile_path.domain
        assert profile_str.subtype   == profile_path.subtype
        assert profile_str.execution == profile_path.execution